name: Docker image build and deploy
# Build & deployment workflow to build a Docker image, log into the VPS server, and
# run a Docker container
on:
  # push:
  #   branches:
  #     - main
  #     - master
  pull_request:
    branches: main
    types: [closed, labeled]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug    
  
env:
  REGISTRY: ghcr.io
  SHOULD_DEPLOY: ${{  ( github.event_name == 'pull_request' && github.event.pull_request.merged == true && 
                       contains(github.event.pull_request.labels.*.name, 'deploy') 
                       ) ||
                      ( 
                        github.event_name == 'pull_request' && github.event.pull_request.merged == true && 
                        github.event.action == 'labeled' && 
                        contains(github.event.pull_request.labels.*.name, 'deploy') 
                       ) ||
                      (
                        github.event_name == 'workflow_dispatch'
                      )
                  }}                  
                  
jobs:
  # env variables are not accessable at job level, so create an output variable to work around this
  prepare:
    runs-on: ubuntu-24.04
    outputs: 
      should_deploy: ${{ env.SHOULD_DEPLOY }}
    steps:
      - name: 
        run: |
          echo "SHOULD_DEPLOY: ${{ env.SHOULD_DEPLOY }}"
          
  # The job continues only if the 'should_deploy' value is true
  build_and_publish:
    runs-on: ubuntu-24.04
    if: needs.prepare.outputs.should_deploy == true
    permissions:
      contents: read
      packages: write
      
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log into package/image registry (${{ env.REGISTRY }})
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker-specific env variables
      # NOTE! env variables defined in a step cannot be referenced until another step, hence the 
      # need for separate steps
      - name: Convert GitHub username to lowercase
        run: |
          echo "REPO_USERNAME_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image name (image 'tag')
        run: |
          echo "IMAGE_REPO_NAME_LC=$(echo '${{ env.REGISTRY }}/${{ env.REPO_USERNAME_LC }}/${{ github.event.repository.name }}')" >> $GITHUB_ENV
          
      - name: Assign version (tag)
      # Assigns 'latest' as default
        run: |
          echo "TAG_NAME=latest" >> $GITHUB_ENV
          echo "REPO_USERNAME_CL: ${{ env.REPO_USERNAME_LC }}"
          echo "IMAGE_REPO_NAME_LC: ${{ env.IMAGE_REPO_NAME_LC }}"
          
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     file: Dockerfile
      #     context: .
      #     push: ${{ github.event_name  != 'pull_request' }}
      #     tags: ${{ env.IMAGE_REPO_NAME_LC }}:${{ env.TAG_NAME }}

  # Run the deployment actions if the build/package job completed successfully
  deploy:
    runs-on: ubuntu-24.04
    needs: build_and_publish
    steps:
      - name: Deploy to server
        run: echo "**Job 'deploy' has run**"
        
        # uses: appleboy/ssh-action@v1
        # with:
        #   host: ${{ secrets.SSH_HOST }}
        #   port: ${{ secrets.SSH_PORT }}
        #   username: ${{ secrets.SSH_USER }}
        #   password: ${{ secrets.SSH_PASSWORD }}
        #   script: |
        #     echo ${{ secrets.GHCR_TOKEN }} | docker login ${{ env.REGISTRY}} -u ${{ env.REPO_USERNAME_LC }} --password-stdin
        #     docker image pull ${{ env.IMAGE_REPO_NAME_LC }}:${{ env.TAG_NAME }}
        #     docker container stop api
        #     docker container rm api
        #     docker container run -d --name api -p 8000:8000 ${{ env.IMAGE_REPO_NAME_LC }}

